language: go
sudo: false

go:
  - 1.8.x
  - master

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install

script:
  - make test
  - make bench

notifications:
  email: false
